### ISSUE TITLE
blockchain intial download fail

### ISSUE THREAD

**Issue by geestar** [firestrand/DownloadBlockChainHeaders#1]
So I will start off by saying Im a little in over my head. Im running a macbook pro 2012 and im no where well versed in programming code.
My issue. Downloaded ethereum wallet and deposited with the bitcoin option 5 days ago. My computer attempted to download the blockchains and was very slow. Prolly due to my duo computer processor. Day 5 and now attempted for the 4th time a full download of the block chain but no success. got to 99% and it started over to 3.5million blocks. And the cycle continues.
I deposited a 1k to ethereum but have no way of retrieving it yet. little worried. 
Am I going to have to buy a new computer or is this a common issue and resolveable?

**Comment by firestrand** [comment]
The code in this repository is just to download the block chain headers, not the actual blockchain. Wallet software can take a LONG time to download the blockchain. Check for issues with the wallet software, or post to somewhere more applicable to your problem.
